# permissions for end users to view tritoninterfaceservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: toolkit-new
    app.kubernetes.io/managed-by: kustomize
  name: tritoninterfaceserver-viewer-role
rules:
- apiGroups:
  - ai-toolkit.ibm.com
  resources:
  - tritoninterfaceservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai-toolkit.ibm.com
  resources:
  - tritoninterfaceservers/status
  verbs:
  - get
