name: workflow-test

on:
  workflow_dispatch:  # This is required for manual triggers
    inputs:
      version:
        description: 'Version number'
        required: true
        default: ‘0.0.3’
      development-tag:
        description: 'Is this a development tag?'
        required: true
        default: ‘true’

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      my_env_var: ${{ steps.set_env.outputs.my_env_var }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variable based on condition
        id: set_env
        run: |
          if [ "${{ github.event.inputs.development-tag }}" == "true" ]; then
            echo "my_env_var=${{ github.event.inputs.version }}-dev” >> $GITHUB_OUTPUT
          else
            echo "my_env_var=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Print environment variable
        run: echo "MY_ENV_VAR is set to: ${{ steps.set_env.outputs.my_env_var }}"

      - name: Print all environment variables
        run: env

